[build]
  command = "dotnet publish -c Release -o bin/Release/net6.0/publish/"
  publish = "bin/Release/net6.0/publish/"

[[plugins]]
  package = "@netlify/plugin-functions-core"

[build.environment]
  NETLIFY_AUTH_TOKEN = "${NETLIFY_AUTH_TOKEN}"
  NETLIFY_SITE_ID = "${NETLIFY_SITE_ID}"
