[build]
  command = "dotnet publish -c ."
  publish = "."

[[plugins]]
  package = "@netlify/plugin-functions-core"

[build.environment]
  NETLIFY_AUTH_TOKEN = "${NETLIFY_AUTH_TOKEN}"
  NETLIFY_SITE_ID = "${NETLIFY_SITE_ID}"
