// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_Ban_Giay_Asp_Net_Core.Entities;

#nullable disable

namespace Web_Ban_Giay_Asp_Net_Core.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Web_Ban_Giay_Asp_Net_Core.Entities.TestTable", b =>
                {
                    b.Property<int>("id_test")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("name_test")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_test");

                    b.ToTable("TestTables");
                });
#pragma warning restore 612, 618
        }
    }
}
